# Generated by Django 3.1.6 on 2021-02-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='balance',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.IntegerField(max_length=16, unique=True),
        ),
    ]
